oder/urls.py
from django.urls import path
from .views import add_to_cart , oder_list , cheakout
app_name = 'oder'
urlpatterns = [
    path('',oder_list,name='oder_list'),
    path('cheakout',cheakout,name='cheakout'),
    path('add-to-cart', add_to_cart , name="add_to_cart"),
]

products/urls.py
from django.urls import path
from .views import ProudctView , ProudctDetail , BrandDetail , BrandView , CatgoryList , tester , add_review
from .api import  ProudctList , ProudctDetil_Api , CatgoryDetil_Api , BrandList_api , CatgoryList_api , BrandDetil_Api
app_name = 'products'
urlpatterns = [
    path('', ProudctView.as_view() , name="proudct_list"),
    path('test', tester , name="test"),
    path('<int:pk>', ProudctDetail.as_view() , name="Detail_list"),
    path('<int:id>/add_review', add_review , name="add_review"),
    path('brand', BrandView.as_view() , name="brand_list"),
    path('brand/<int:pk>', BrandDetail.as_view() , name="brand_Detail"),
    path('catgory', CatgoryList.as_view() , name="catgory_list"),
    ####    API    ################
    path('api/proudct/', ProudctList.as_view()),
    path('api/proudct/<pk>', ProudctDetil_Api.as_view()),
    path('api/brand/', BrandList_api.as_view()),
    path('api/brand/<int:pk>', BrandDetil_Api.as_view()),
    path('api/catgory/', CatgoryList_api.as_view()),
    path('api/catgory/<int:pk>', CatgoryDetil_Api.as_view()),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path("accounts/", include("accounts.urls", namespace = 'accounts' )),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('shop/', include('products.urls' , namespace='products')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'), 
    path('oder/', include('oder.urls' , namespace='oder')),
    path('summernote/', include('django_summernote.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from taggit.managers import TaggableManager
from django.utils import timezone

PRODECT_FLAG = (

    ('New' , 'New'),
    ('Sale' , 'Slae'),
    ('Fature' , 'Fature')

)

# product database.
class Products(models.Model):
    name = models.CharField(_('Name') , max_length=100)
    sku = models.IntegerField(_('SKU'))
    price = models.FloatField(_('Price'))
    image = models.ImageField(upload_to = 'proudcts')
    brand = models.ForeignKey('Brand' , on_delete= models.SET_NULL  , null=True , blank= True , verbose_name= _('Brand') , related_name='brand_product')
    rate = models.IntegerField(_('Rate'))
    dec = models.TextField(_('dec') , max_length=300)
    subtitle = models.CharField(_('subtitle') , max_length=150)
    tags = TaggableManager()
    flags = models.CharField( _('Flags'), max_length=10 , choices= PRODECT_FLAG ,)
    catgory = models.ForeignKey('Catgory' , on_delete= models.SET_NULL , null= True , blank= True , related_name='Catgory_prodcut', verbose_name=_('Catgory'))
    video_url = models.URLField(_('video_url'), null=True , blank=True)
    
    
    def __str__(self) -> str:
        return self.name
    

class ProductsImages(models.Model):
    products = models.ForeignKey(Products ,  verbose_name=_('Product_image') , on_delete= models.CASCADE)
    images = models.ImageField(_("image") , upload_to = 'productimages')
    def __str__(self) -> str:
        return str(self.products)


class Catgory(models.Model):
    name = models.CharField( _('Catgory_name') ,max_length=50)
    image = models.ImageField(_('Catgory_images') , upload_to = 'Cagtory')
    def __str__(self) -> str:
        return self.name


class Brand(models.Model):
    name = models.CharField( _('Brand_name'),max_length=50)
    image = models.ImageField(_('Brand_images') , upload_to = 'Brand')
    def __str__(self) -> str:
        return self.name


class Reviw(models.Model):
    user = models.ForeignKey(User , on_delete= models.SET_NULL , null=True , blank=True , verbose_name= _('user'))
    products = models.ForeignKey(Products , related_name = 'Proudct_Review' , on_delete=models.SET_NULL , null=True , blank= True,verbose_name=_('product' ))
    commnt = models.CharField(_('commnet') ,max_length=300)
    rate = models.IntegerField(_('Rate'))
    create_at = models.DateField(default=timezone.now, verbose_name=_('create_at'))
    def __str__(self) -> str:
        return str(self.products)

products/views.py
from django.shortcuts import render
from django.views.generic import ListView , DetailView
from .models import Products , ProductsImages , Brand , Catgory , Reviw
from django.db.models import Count , Q , F , Value
from django.db.models.aggregates import Min , Max , Sum , Avg
from django.db.models.functions import Concat
from .froms import ProudctReviewFrom
def tester(request):
    obj = Products.objects.all()
    #obj = Products.objects.filter(price__range = (0,100))
    #obj = Products.objects.filter(price__range = (0,100)).order_by('-name')
    #obj = Products.objects.select_related('brand').all().order_by('-price')
    #obj =   Products.objects.select_related('brand').filter()
    #obj = Products.objects.filter(Q(name__endswith = 'S') & Q(price__lt = 80))
    #obj = Products.objects.filter(flag__isnull = True)
    #obj = Products.objects.filter(Q(qounitiy__lt = 50) & Q(price__lt = 70))
    #obj = Products.objects.filter(qounitiy = F('price'))
    #obj = Products.objects.filter(qounitiy = F('catgory__id'))
    #obj = Products.objects.values('name' , 'catgory' , 'catgory__id' , 'price')
    #obj = Products.objects.only('name' , 'catgory')
    #obj = Products.objects.annotate(is_new = Value(True))
    #obj = Products.objects.annotate(
    #    full_name = Concat('name' , Value(' ') , 'flags' )
    #)
    return render(request , 'products/test.html' , {'test':obj})
class ProudctView(ListView):
    model = Products
    paginate_by = 100
class ProudctDetail(DetailView):
    model = Products

    def get_context_data(self , **kwargs):
        context = super().get_context_data(**kwargs)
        myproducts = self.get_object()
        context['images'] = ProductsImages.objects.filter(products=myproducts)
        context['realated'] = Products.objects.filter(catgory = myproducts.catgory)
        context['review'] = Reviw.objects.filter(products = myproducts)
        #context['review_count'] = Reviw.objects.all().annotate(product_count = Count('Proudct_Review'))
        return context
class BrandView(ListView):
    model = Brand

    def get_context_data(self , **kwargs):
        context = super().get_context_data(**kwargs)
        context['brand'] = Brand.objects.all().annotate(product_count = Count('brand_product'))
        return context


class BrandDetail(DetailView):
    model = Brand
    def get_context_data(self , **kwargs):
        context = super().get_context_data(**kwargs)
        brand = self.get_object()
        context['brandc'] = Brand.objects.all().annotate(brand_count = Count('brand_product'))
        return  context 

class CatgoryList(ListView):
    model = Catgory
    def get_context_data(self , **kwargs):
        context = super().get_context_data(**kwargs)
        context['catgory'] = Catgory.objects.all().annotate(product_count = Count('Catgory_prodcut'))
        return context

from django.template.loader import render_to_string
from django.http import JsonResponse
def add_review(request,id):
    proucts =  Products.objects.get(id=id)
    if request.method == 'POST':
        form = ProudctReviewFrom(request.POST)
        if form.is_valid():
            myfrom = form.save(commit=False)
            myfrom.products = proucts
            myfrom.user = request.user
            myfrom.save()
            review = Reviw.objects.filter(products=proucts)
            html = render_to_string('include/reviews.html',{"review":review , request:request})
            return JsonResponse({"resulat":html})

products/templates/products/brand_detail.html
{% extends 'base.html' %}
{% load static %}
    {% block 'css'%}
        <link rel="stylesheet" href="{% static 'css/brand-single.css' %}">
    {% endblock 'css'%}
{% block 'body' %}
        <!--=== ==================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="brand-list.html">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand}}</h3></a>
            <ul>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star"></li>
                <li class="total">(163 ratings)</li>
            </ul>
            <p>( {{brand.brandc.brand_product}} items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                {% for proudct in brandc %}
                    <div class="col">
                        <div class="product-card">
                            <div class="product-media">
                                <div class="product-label">
                                    <label class="label-text new">{{proudct.flags}}</label>
                                </div>
                                <button class="product-wish wish">
                                    <i class="fas fa-heart"></i>
                                </button>
                                <a class="product-image" href="{% url 'products:Detail_list' proudct.id %}">
                                    <img src="{{proudct.image.url}}" alt="product">
                                </a>
                                <div class="product-widget">
                                    <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                    <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                    <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                </div>
                            </div>
                            <div class="product-content">
                                <div class="product-rating">
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="icofont-star"></i>
                                    <a href="{% url 'products:Detail_list' proudct.id %}">(3)</a>
                                </div>
                                <h6 class="product-name">
                                    <a href="{% url 'products:Detail_list' proudct.id %}">{{proudct}}</a>
                                </h6>
                                <h6 class="product-price">
                                    <del>$34</del>
                                    <span>${{proudct.price}}<small>/piece</small></span>
                                </h6>
                                <button class="product-add" title="Add to Cart">
                                    <i class="fas fa-shopping-basket"></i>
                                    <span>add</span>
                                </button>
                                <div class="product-action">
                                    <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                    <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                    <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}   
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        

{% endblock 'body' %}

products/templates/products/brand_list.html
{% extends 'base.html' %}
{% block 'body' %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    <option value=".vegetables">vegetables</option>
                                    <option value=".fruits">fruits</option>
                                    <option value=".drinks">drinks</option>
                                    <option value=".fishes">fishes</option>
                                    <option value=".meats">meats</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                {% for brands in brand %}
                    <div class="col all vegetables">
                        <div class="brand-wrap">
                            <div class="brand-media">
                                <img src="{{brands.image.url}}" alt="brand">
                                <div class="brand-overlay">
                                    <a href="{% url 'products:brand_Detail' brands.id %}"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="brand-meta">
                                <h4>{{brands}}</h4>
                                <p>({{brands.product_count}} items)</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->
{% endblock 'body' %}

products/templates/products/catgory_list.html
{% extends 'base.html' %}
    {% load static %}
        {% block 'css'%}
        <link rel="stylesheet" href="{% static 'css/all-category.css' %}">
        {% endblock 'css'%}

{% block 'body' %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>all category</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">all-category</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    CATEGORY PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 justify-content-center">
                {% for catgory in catgory %}
                    <div class="col">
                        <div class="category-wrap">
                            <div class="category-media">
                                <img src="{{catgory.image.url}}" alt="category">
                                <div class="category-overlay">
                                    <a href="shop-3column.html"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="category-meta">
                                <h4>{{catgory}}</h4>
                                <p>({{catgory.product_count}} items)</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    CATEGORY PART END
        =======================================-->

{% endblock 'body' %}
 

products/templates/products/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for proud in test %}
        <p>{{proud}}</p>
    {% endfor %}
</body>
</html>